### ISSUE TITLE
Awesome tutorial!

### ISSUE THREAD

**Issue by JonasL5** [panzerdp/dmitripavlutin.com-comments#93]
It was really great and nicely explained, thanks a lot for your work!
I'd just like to point out something that doesn't seem accurate to me:

In the creation array section:
"Notice that cloning happens only on the array itself, but not on the contained elements (i.e. it’s not a deep clone)"
I believe the exact equality === doesn't work because it's not the same prototype (object). It's a new box with the same elements, so == should work. So your "happens only on the array itself" doesn't seem right and should be something like:
"Notice that cloning happens only to the contained elements, the array itself has a new prototype" (aka; same elements, different box)

Or that's how I understand it at least ;)

**Comment by panzerdp** [comment]
Thanks for your suggestion. But I'd keep the original text.
